<a href="https://colab.research.google.com/github/nipunmah/cognitive-computing/blob/main/assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)
print("Addition:", arr + 2)
print("Multiplication:", arr * 3)
print("Division:", arr / 2)

Original array: [10 20 30 40 50]
Addition: [12 22 32 42 52]
Multiplication: [ 30  60  90 120 150]
Division: [ 5. 10. 15. 20. 25.]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [3]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

for arr in [x, y]:
    values, counts = np.unique(arr, return_counts=True)
    max_count = counts.max()
    frequent = values[counts == max_count]

    print("\nArray:", arr)
    print("Most frequent value:", frequent)

    for value in frequent:
        print("Indices:", np.where(arr == value)[0])


Array: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: [1]
Indices: [0 5 7 8 9]

Array: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: [1 3]
Indices: [0 1 2]
Indices: [4 8 9]


In [4]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [5]:
import numpy as np

nipun = np.linspace(10, 100, 25)

print("Array:")
print(nipun)

print("Dimensions:", nipun.ndim)
print("Shape:", nipun.shape)
print("Total elements:", nipun.size)
print("Data type:", nipun.dtype)
print("Total bytes:", nipun.nbytes)

transpose_nipun = nipun.reshape(25, 1)

print("Transpose using reshape:")
print(transpose_nipun)

print("Using T attribute:")
print(nipun.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
import numpy as np

ucs420_nipun = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Array:")
print(ucs420_nipun)

print("Mean:", np.mean(ucs420_nipun))
print("Median:", np.median(ucs420_nipun))
print("Maximum:", np.max(ucs420_nipun))
print("Minimum:", np.min(ucs420_nipun))
print("Unique elements:", np.unique(ucs420_nipun))

reshaped_ucs420_nipun = ucs420_nipun.reshape(4, 3)

print("\nReshaped array:")
print(reshaped_ucs420_nipun)

resized_ucs420_nipun = np.resize(ucs420_nipun, (2, 3))

print("\nResized array:")
print(resized_ucs420_nipun)

Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array:
[[10 20 30]
 [40 50 60]]
